Repository S2U2MLancer/show-me-blog, pull requests merged in 2019-06, with the labels that each got.

#18 set up docker-compose for nginx
  deploy/.gitignore
  deploy/docker-compose.yml
  deploy/nginx/config/conf.d/default.conf
  deploy/nginx/config/fastcgi_params
  deploy/nginx/config/koi-utf
  deploy/nginx/config/koi-win
  deploy/nginx/config/mime.types
  deploy/nginx/config/nginx.conf
  deploy/nginx/config/scgi_params
  deploy/nginx/config/sites-enabled/default
  deploy/nginx/config/sites-enabled/show-me
  deploy/nginx/config/uwsgi_params
  deploy/nginx/config/win-utf
  deploy/nginx/log/.gitkeep
  deploy/nginx/web/show-me/.gitkeep
Labels: Ops

#20 set up basic server
  server/.gitignore
  server/pom.xml
  server/src/main/java/com/s2u2m/prod/showme/ShowMeServerApp.java
  server/src/main/java/com/s2u2m/prod/showme/config/SwaggerConfig.java
  server/src/main/java/com/s2u2m/prod/showme/controller/IndexController.java
  server/src/main/resources/application.properties
  server/src/test/java/.gitkeep
Labels: Dev

#22 add static code analysis by travis
  .travis.yml
  README.md
  sonar-project.properties
Labels: Ops

#25 add postman API test demo
  test/.gitkeep
  test/API_test_suite/.gitkeep
  test/API_test_suite/readme.md
  test/API_test_suite/show-test.postman_environment.json
  test/API_test_suite/testsuite.postman_collection.json
Labels: QA

#24 setup ui test framework
  .gitignore
  test/Smoking_test_suite/README.md
  test/Smoking_test_suite/config/__init__.py
  test/Smoking_test_suite/config/base.py
  test/Smoking_test_suite/config/environment.py
  test/Smoking_test_suite/log/__init__.py
  test/Smoking_test_suite/page/__init__.py
  test/Smoking_test_suite/page/getDriver.py
  test/Smoking_test_suite/page/homePage.py
  test/Smoking_test_suite/report/.gitkeep
  test/Smoking_test_suite/requirements.txt
  test/Smoking_test_suite/resources/.gitkeep
  test/Smoking_test_suite/scripts/.gitkeep
  test/Smoking_test_suite/testcases/__init__.py
  test/Smoking_test_suite/testcases/testtitle.py
  test/Smoking_test_suite/testsuite/__init__.py
  test/Smoking_test_suite/testsuite/testall.py
  test/Smoking_test_suite/utils/__init__.py
  test/Smoking_test_suite/utils/checkplantfram.py
  test/Smoking_test_suite/utils/downloaddriver.py
  test/Smoking_test_suite/utils/findelement.py
  test/Smoking_test_suite/utils/logfuction.py
Labels: QA
